name = "codsen-com"
type = "webpack"
account_id = "4dad28d388d3aab5371492d4a8877881"
workers_dev = true
route = "codsen.com/*"
zone_id = "f928fdd5df8ad23e4e384769e712f251"

[site]
bucket = "./dist"
entry-point = "workers-site"
